# Generated by Django 3.1.7 on 2021-03-11 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0002_auto_20210309_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countermodel',
            name='count',
            field=models.IntegerField(verbose_name='count'),
        ),
    ]
