# Generated by Django 3.1.7 on 2021-03-11 09:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('urlShortApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shorturl',
            options={'verbose_name': 'URL Entry', 'verbose_name_plural': 'URL Entries'},
        ),
        migrations.RemoveField(
            model_name='shorturl',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='shorturl',
            name='expire_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='expire_date'),
            preserve_default=False,
        ),
    ]
