# Generated by Django 3.1.7 on 2021-03-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlShortApp', '0005_auto_20210322_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='clicks',
            field=models.IntegerField(default=0, null=True, verbose_name='Click count'),
        ),
    ]
